# Generated by Django 4.1.2 on 2022-10-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengunjung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='jumlah',
        ),
    ]
